### PR TITLE
Image support

### PR DESCRIPTION
**Pull request by chelseyeslehc**
Added image support and merged Redux improvements.

### CODE REVIEW

**Comment by ChristianEdwardPadilla** [comment]
This looks like it's trying to add image support for the Rectangles? But I think it will just have the effect of adding an image to the canvas background, probably over the top of the grid.

If what you're going for is for the user to be able to specify an image for each component (and have that reflected in the component's Rectangles) you should look into adding the image source as a property on the Rectangle. We had this working to some extent at some point but stripped it out for some reason. Looking back thru the commits might actually be useful in this case.

**Comment by chelseyeslehc** [comment]
> This looks like it's trying to add image support for the Rectangles? But I think it will just have the effect of adding an image to the canvas background, probably over the top of the grid.
> 
> If what you're going for is for the user to be able to specify an image for each component (and have that reflected in the component's Rectangles) you should look into adding the image source as a property on the Rectangle. We had this working to some extent at some point but stripped it out for some reason. Looking back thru the commits might actually be useful in this case.

We actually added image support for the prototyping/mockup image as it wasn't working before! With this update, the user can upload a mockup as the background image and then create all of their components on top of that image.

**Comment by ChristianEdwardPadilla** [comment]
That makes sense.
LGTM

**Comment by ChristianEdwardPadilla** [comment]
Also, FYI, when you all are done, if you're interested, make a PR to merge this with the OSLabs version.

Also, add yourselves as contributors to the readme.

Also, make a PR to the website (reactype.io) if you'd like:  https://github.com/team-reactype/ReacTypeWeb/blob/master/docs/index.html

**Pull request closed without merging**
